create sequence hibernate_sequence start 1 increment 1;
create table auth_token_data_dto (expiration_date_utc timestamp not null, auth_token varchar(255), primary key (expiration_date_utc));
create table bus_stop (id int4 not null, name varchar(255) not null, primary key (id));
create table cashier (id int4 not null, inn varchar(255), name varchar(255), primary key (id));
create table customer_receipt (id int4 not null, bill_address varchar(255), email varchar(255), kktfa boolean, payment_type int4, phone varchar(255), taxation_system varchar(255), primary key (id));
create table customer_receipt_items (customer_receipt_id int4 not null, items_id int4 not null);
create table item (id int4 not null, amount float8, customs_declaration_number varchar(255), label varchar(255), marking_code varchar(255), origin_country_code varchar(255), payment_method int4, payment_type int4, price float8, quantity int4, vat varchar(255), primary key (id));
create table ofd_configure (id int4 not null, bill_address varchar(255), company_inn varchar(255), company_name varchar(255), default_payment_method int4 not null, default_payment_type int4 not null, default_vat varchar(255), kktfa boolean not null, name varchar(255), service_password varchar(255), service_url varchar(255), service_user varchar(255), taxation_system varchar(255), primary key (id));
create table receipt_id_data_dto (receipt_id varchar(255) not null, primary key (receipt_id));
create table route (id int4 not null, number varchar(255), end_point_id int4, start_point_id int4, primary key (id));
create table route_bus_stops (route_id int4 not null, bus_stops_id int4 not null);
create table status_data_device_dto (id int4 not null, device_id varchar(255), fdn varchar(255), fn varchar(255), fpd varchar(255), rnm varchar(255), zn varchar(255), primary key (id));
create table status_data_dto (id int4 not null, modified_date_utc timestamp, receipt_date_utc timestamp, status_code int4 not null, status_message varchar(255), status_name varchar(255), status_data_device_dto_id int4, primary key (id));
create table ticket (id int4 not null, date timestamp, price float8 not null, type varchar(255), cheque_id int4, end_point_id int4, ofd_configure_id int4 not null, start_point_id int4, trip_id int4, primary key (id));
create table trip (id int4 not null, start_date timestamp not null, route_id int4 not null, primary key (id));
create table user_role (user_id int4 not null, roles varchar(255));
create table usr (id int4 not null, activation_code varchar(255), active boolean not null, email varchar(255), full_name varchar(255), password varchar(255), username varchar(255), primary key (id));
create table сheque (id int4 not null, inn varchar(255), invoice_id varchar(255), local_date varchar(255), receipt_id varchar(255), type varchar(255), cashier_id int4 not null, customer_receipt_id int4 not null, status_data_dto_id int4, primary key (id));
alter table if exists customer_receipt_items add constraint UK_exryx9l84yfvko5251l9j8dyh unique (items_id);
alter table if exists customer_receipt_items add constraint FKmv2s44shnb55l53twauoym2i2 foreign key (items_id) references item;
alter table if exists customer_receipt_items add constraint FK8qf6bsfadl9k4qsv8e0077ugh foreign key (customer_receipt_id) references customer_receipt;
alter table if exists route add constraint FKee9ain5226yrmhhhd04yfqb3m foreign key (end_point_id) references bus_stop;
alter table if exists route add constraint FKqxc39a6mttpcmbsabrwwasiyd foreign key (start_point_id) references bus_stop;
alter table if exists route_bus_stops add constraint FKcb48j3lya1jxji3ny0vq9tbkj foreign key (bus_stops_id) references bus_stop;
alter table if exists route_bus_stops add constraint FKmiixkj29nyyehgn6rcurgvwnh foreign key (route_id) references route;
alter table if exists status_data_dto add constraint FK7fkjfqytiyd0mg963162t7s5n foreign key (status_data_device_dto_id) references status_data_device_dto;
alter table if exists ticket add constraint FKbl0yfxebexk1lx2kpf23yv5hn foreign key (cheque_id) references сheque;
alter table if exists ticket add constraint FKo84mv5ulqrvukme1bqkq9eig2 foreign key (end_point_id) references bus_stop;
alter table if exists ticket add constraint FKey4vs3r5a5cng8ob80teisk47 foreign key (ofd_configure_id) references ofd_configure;
alter table if exists ticket add constraint FKsoiu3y65qsnin729bnq0evcdl foreign key (start_point_id) references bus_stop;
alter table if exists ticket add constraint FKjp9yu1pw75obvo1aaao6os7vk foreign key (trip_id) references trip;
alter table if exists trip add constraint FKeva4adpyk6glllffnw5ypj20j foreign key (route_id) references route;
alter table if exists user_role add constraint FKfpm8swft53ulq2hl11yplpr5 foreign key (user_id) references usr;
alter table if exists сheque add constraint FK9eaqb7w9rbh8ucl3u05jlrqx5 foreign key (cashier_id) references cashier;
alter table if exists сheque add constraint FKfyjbvoe5dj5ure5ffpt6lniaw foreign key (customer_receipt_id) references customer_receipt;
alter table if exists сheque add constraint FK30y9bnxyrchmhbj560gppmcxd foreign key (status_data_dto_id) references status_data_dto;